[package]
id = "msv44hokzr4os6ndsi6sj6jynbp2ruij"
name = "Dead Meets Lead Content"
version = "0.0.1"
content = { type = "Asset", models = true, animations = true }
ambient_version = "0.3.1-nightly-2023-10-20"
